Implement filter by ids
freakboy3742/pyxero pull request #300
Opened 2020-08-19 09:49 UTC by bartonip

Requested by: #267 
Xero offers a fast way to select multiple invoices by using the `IDs` param. This has been added to the `_filter` method.

[https://developer.xero.com/documentation/api/requests-and-responses](https://developer.xero.com/documentation/api/requests-and-responses)

Usage:
```
xero.invoices.filter(IDs='f3ecf55f-b7b0-47d2-a0f3-97df84890af2,f3ecf55f-b7b0-47d2-a0f3-97df84890af2f3ecf55f-b7b0-47d2-a0f3-97df84890af2')
```

2020-08-26 23:20 UTC, bartonip commented
@freakboy3742  bump

2020-08-26 23:48 UTC, freakboy3742 requested changes
I feel like we can provide a much more Pythonic API here. The Xero API may expose "IDs" as a comma separated string, but that doesn't mean PyXero's API needs to be the same. Otherwise, there's no benefit over using `raw`. 

I'd expect the public API for `IDs` to be a list of strings, concatenated *internally* to a single string.

2020-08-27 08:51 UTC, bartonip commented
@freakboy3742 done

2020-08-30 02:29 UTC, freakboy3742 approved these changes
Looks good - thanks for the patch!

2020-08-30 02:30 UTC, merged